### PR TITLE
Modified for domain handling

### PR DESCRIPTION
**Pull request by tcarolanthycotic**
Added some specific handling for an additional parameter for domain users for on-premise Secret Server.

### CODE REVIEW

**Comment by jamesooo** [comment]
It would be great to see this feature. Since this is currently missing my team hasn't been able to do much good automation with our on premise ss but there is a LOT that id like to do

**Comment by tcarolanthycotic** [comment]
@jamesooo Nothing has been added feature-wise. This is just a minor change to code to add support for domain credentials, but I wouldn't necessarily recommend using domain credentials for this sort of authentication anyway. Theoretically one should be using "Application API" account credentials instead.

**Comment by andyewing** [comment]
I second adding this feature. Application API accounts don't work well for all automation use cases. Often domain credentials are already available to whatever system is automating a workflow, because a user has to log in to an orchestration tool to start the automation workflow.

In those cases it's easier (and possibly more secure, in terms of tying actions to specific users) to leverage AD credentials than to figure out how to securely store and provision Application API account credentials in each orchestration tool.

**Comment by wsmelton** [comment]
@tcarolanthycotic the VS files need to be removed from the PR.

**Comment by geoff-carr-bzy** [comment]
Any chance this can be merged now? This is really key functionality since SecretServer supports AD authentication.

**Comment by EndlessTrax** [comment]
Adding support for domain users is definitely something that should be added to this SDK. However, this PR currently introduces breaking changes for cloud users and cannot be merged. 

We have an update coming that will add this feature. I will comment further and close this issue when it is available/merged.

**Comment by EndlessTrax** [comment]
Domian Authentication is now available in the latest release 0.0.6. Thank you all.

**Pull request closed without merging**
